package academy.devdojo.maratonajava.javacore.Oexception.runtime.test;

public class RunTimeExceptionTest02 {
    public static void main(String[] args) {

        divisao(1,0);

        System.out.println("C처digo finalizado");
    }

    /**
     * @param a
     * @param b n찾o pode ser zero
     * @return divis찾o
     * @throws IllegalArgumentException caso b seja zero
     */
    private static int divisao(int a, int b) {
        if(b == 0) {
            throw new IllegalArgumentException("Argumento ilegal, n찾o pode ser zero");
        }
        return a/b;
    }
}
